[package]
name = "wnfs-hamt"
version = "0.2.0"
description = "IPLD HAMT implementation for Webnative Filesystem"
keywords = ["wnfs", "webnative", "ipfs", "decentralisation"]
categories = [
  "filesystem",
  "cryptography",
  "web-programming",
  "wasm",
]
license = "Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/wnfs-wg/rs-wnfs/tree/main/wnfs-hamt"
homepage = "https://fission.codes"
authors = ["The Fission Authors"]

[dependencies]
anyhow = "1.0"
async-once-cell = "0.5"
async-recursion = "1.0"
bitvec = { version = "1.0", features = ["serde"] }
blake3 = { version = "1.4", features = ["traits-preview"] }
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std"] }
either = "1.8"
futures = "0.3"
insta = { version = "1.30", features = ["json"] }
libipld = { version = "0.16", features = ["dag-cbor", "derive", "serde-codec"] }
log = { version = "0.4", optional = true }
multihash = "0.18"
once_cell = "1.16"
proptest = { version = "1.1", optional = true }
rand_core = "0.6"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["rc"] }
serde-byte-array = "0.1.2"
serde_bytes = "0.11.12"
serde_ipld_dagcbor = "0.4.2"
testresult = "0.3.0"
thiserror = "1.0"
wnfs-common = { path = "../wnfs-common", version = "=0.2.0" }

[dev-dependencies]
async-std = { version = "1.11", features = ["attributes"] }
insta = "1.30"
proptest = "1.1"
rand = "0.8"
serde_json = "1.0.103"
test-strategy = "0.3"
wnfs-common = { path = "../wnfs-common", features = ["test_utils"] }

[features]
test_utils = ["proptest"]
